# ARTIFACTS ARE NOTHING BUT FILES THAT ARE CREATED DURING THE WORKFLOW RUN OR WHEN A BUILD SCRIPT IS RUN

# The files that are created when we run the build script are called artifacts.
# dist folder files like index.html, main.js, main.css and assets are artifacts.

name: Artifacts Demo
on:
  push:
    branches:
      - main
jobs:
  # JOB 1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from GitHub
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
  # JOB 2
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code from GitHub
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: dist
  # JOB 3
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
      - name: List files
        run: ls
      - name: Deploy
        run: echo "Deploying!"
