# uses is a common key for all actions
# and run is the command to run the action on a command line or shell

name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from GitHub
        uses: actions/checkout@v3
      # Already installed on the runner but we can use it to install other versions
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        # ci is used to install dependencies in a clean environment (no package-lock.json)
        run: npm ci
      - name: Run tests
        run: npm test
